apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "421a5f51-b908-4a0c-bde2-6c88f8f4a8bb"
  name: "cosmosdb-order-processor-sa"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmosdb-order-processor
  labels:
    aadpodidbinding: "cosmosdb-order-processor-identity"
    app: cosmosdb-order-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cosmosdb-order-processor
  template:
    metadata:
      labels:
        app: cosmosdb-order-processor
        aadpodidbinding: "cosmosdb-order-processor-identity"
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: "cosmosdb-order-processor-sa"
      containers:
        - name: mycontainer
          image: sandboxcosmosakskeda.azurecr.io/cosmosdb/order-processor:latest # update as per your environment, example myacrname.azurecr.io/cosmosdb/order-processor:latest. Do NOT add https:// in ACR Name
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.5"
              memory: "500Mi"
          env:
            - name: CosmosDbConfig__Endpoint
              value: https://sandbox-cosmos-aks-keda.documents.azure.com:443/ # update as per your environment
            - name: CosmosDbConfig__LeaseEndpoint
              value: https://sandbox-cosmos-aks-keda.documents.azure.com:443/ # update as per your environment

